# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc ""
  homepage "https://github.com/marianina8"
  version "0.1"

  on_macos do
    url "https://github.com/marianina8/cli/releases/download/v0.1/cli_Darwin_all.tar.gz"
    sha256 "988d7d2d90e916bc670e6172d73c946799c28a288b4a2561c48e5f87dc0d50bb"

    def install
      bin.install "cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marianina8/cli/releases/download/v0.1/cli_Linux_arm64.tar.gz"
      sha256 "09af81c75301f0592dd8628199a588f13dfb96d030abeae719c4bd491756a0b0"

      def install
        bin.install "cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marianina8/cli/releases/download/v0.1/cli_Linux_x86_64.tar.gz"
      sha256 "2a6a498154a3440c7dadbdc568cee684f352e48743aceaa6ec7e70955280288d"

      def install
        bin.install "cli"
      end
    end
  end
end
